{
 "title": "Application Logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "thread_name",
    "label": "thread_name",
    "query": "{\"find\": \"terms\", \"field\":\"thread_name.keyword\"}"
   },
   {
    "name": "app_node",
    "label": "app_node",
    "query": "{\"find\": \"terms\", \"field\":\"app_node.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs Detail -  $thread_name",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "thread_name:\"$thread_name\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs Detail -  $app_node",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "app_node:\"$app_node\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Timeline Detail",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "INFO",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "level:INFO",
     "timeField": "@timestamp"
    },
    {
     "alias": "WARN",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "level:WARN",
     "timeField": "@timestamp"
    },
    {
     "alias": "ERROR",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "level:ERROR",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}